// Api Url
//export const API_URL = "https://cosound.geekydev.com/backend/api/";
//export const API_URL = "http://cosound.local.geekydev.com/api/";
//export const API_URL = "http://localhost:8000/api/";

export const API_URL = "https://cosound.geekydev.com/backend/api/";


export const GETSTREAM_API_KEY = "abpggps8m5sv";
export const GETSTREAM_APP_ID = "43333";
export const GETSTREAM_REGION = "us-east";

// WOW with animate.css
export const INITIALIZE_WOW = "INITIALIZE_WOW";
export const SYNC_WOW = "SYNC_WOW";

// Sign up constants
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// Fetch Genres
export const GENRES_REQUEST = "GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";

// User
export const SET_USER = "SET_USER";

// Suggestions
export const SUGGESTIONS_REQUEST = "SUGGESTIONS_REQUEST";
export const SUGGESTIONS_SUCCESS = "SUGGESTIONS_SUCCESS";
export const SUGGESTIONS_FAILURE = "SUGGESTIONS_FAILURE";

// Follow-Unfollow
export const FOLLOW_REQUEST = "FOLLOW_REQUEST";
export const FOLLOW_FAILURE = "FOLLOW_FAILURE";
export const FOLLOW_SUCCESS = "FOLLOW_SUCCESS";
export const REFACTOR_SUGGESTIONS = "REFACTOR_SUGGESTIONS";

// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Fetch User Details
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";

// Social User data for signup
export const SET_SOCIAL_USER_DATA = "SET_SOCIAL_USER_DATA";
export const RESET_SOCIAL_DATA = "RESET_SOCIAL_DATA";

export const RESET_FETCH_USER = "RESET_FETCH_USER";

// Forgot Password
export const PASSWORD_FORGOT_REQUEST = "PASSWORD_FORGOT_REQUEST";
export const PASSWORD_FORGOT_SUCCESS = "PASSWORD_FORGOT_SUCCESS";
export const PASSWORD_FORGOT_FAILURE = "PASSWORD_FORGOT_FAILURE";

// Reset Password
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

// Logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

// POST
export const POST_REQUEST = "POST_REQUEST";
export const POST_FAILURE = "POST_FAILURE";
export const POST_SUCCESS = "POST_SUCCESS";

// User Feed
export const USER_FEED_REQUEST = "USER_FEED_REQUEST";
export const USER_FEED_SUCCESS = "USER_FEED_SUCCESS";
export const USER_FEED_FAILURE = "USER_FEED_FAILURE";
export const REFACTOR_USER_FEED = "REFACTOR_USER_FEED";

// Post Like
export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_FAILURE = "LIKE_FAILURE";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const REFACTOR_LIKED_POST = "REFACTOR_LIKED_POST";

// Post Comment and Collaterals
export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const INCREMENT_COMMENT_COUNT_USER_POST =
  "INCREMENT_COMMENT_COUNT_USER_POST";
export const ADD_COMMENT_TO_USER_POST = "ADD_COMMENT_TO_USER_POST";

// Fetch Comments | Per Page : 3
export const FETCH_COMMENT_REQUEST = "FETCH_COMMENT_REQUEST";
export const FETCH_COMMENT_SUCCESS = "FETCH_COMMENT_SUCCESS";
export const FETCH_COMMENT_FAILURE = "FETCH_COMMENT_FAILURE";

// Delete Comment and Collaterals
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
export const REMOVE_FROM_COMMENTS = "REMOVE_FROM_COMMENTS";
export const DECREMENT_COMMENT_COUNT_USER_POST =
  "DECREMENT_COMMENT_COUNT_USER_POST";

// Delete User feed
export const DELETE_USER_FEED_REQUEST = "DELETE_USER_FEED_REQUEST";
export const DELETE_USER_FEED_SUCCESS = "DELETE_USER_FEED_SUCCESS";
export const DELETE_USER_FEED_FAILURE = "DELETE_USER_FEED_FAILURE";

// TEMPORARY FILE
export const SET_TEMPORARY_FILE = "SET_TEMPORARY_FILE";
export const RESET_TEMP_FILE = "RESET_TEMP_FILE";

// My Music
export const FETCH_MY_MUSIC_REQUEST = "FETCH_MY_MUSIC_REQUEST";
export const FETCH_MY_MUSIC_SUCCESS = "FETCH_MY_MUSIC_SUCCESS";
export const FETCH_MY_MUSIC_FAILURE = "FETCH_MY_MUSIC_FAILURE";
export const ADD_TO_MY_MUSIC = "ADD_TO_MY_MUSIC";
export const REFACTOR_MY_MUSIC = "REFACTOR_MY_MUSIC";

// My Images
export const FETCH_MY_IMAGES_REQUEST = "FETCH_MY_IMAGES_REQUEST";
export const FETCH_MY_IMAGES_SUCCESS = "FETCH_MY_IMAGES_SUCCESS";
export const FETCH_MY_IMAGES_FAILURE = "FETCH_MY_IMAGES_FAILURE";
export const ADD_TO_MY_IMAGES = "ADD_TO_MY_IMAGES";
export const REFACTOR_MY_IMAGE = "REFACTOR_MY_IMAGE";

// POST DETAILS
export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAILURE = "POST_DETAILS_FAILURE";

// USER_UPDATE
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAILURE = "USER_UPDATE_FAILURE";

// Change Password
export const PASSWORD_CHANGE_REQUEST = "PASSWORD_CHANGE_REQUEST";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAILURE = "PASSWORD_CHANGE_FAILURE";

// Account Settings
export const CONTACT_INFO_UPDATE_REQUEST = "CONTACT_INFO_UPDATE_REQUEST";
export const CONTACT_INFO_UPDATE_SUCCESS = "CONTACT_INFO_UPDATE_SUCCESS";
export const CONTACT_INFO_UPDATE_FAILURE = "CONTACT_INFO_UPDATE_FAILURE";
export const DETAILS_UPDATE_REQUEST = "DETAILS_UPDATE_REQUEST";
export const DETAILS_UPDATE_SUCCESS = "DETAILS_UPDATE_SUCCESS";
export const DETAILS_UPDATE_FAILURE = "DETAILS_UPDATE_FAILURE";
export const UPDATE_AVATAR_REQUEST = "UPDATE_AVATAR_REQUEST";
export const UPDATE_AVATAR_SUCCESS = "UPDATE_AVATAR_SUCCESS";
export const UPDATE_AVATAR_FAILURE = "UPDATE_AVATAR_FAILURE";

// Dashboard | Feed
export const FEED_REQUEST = "FEED_REQUEST";
export const FEED_SUCCESS = "FEED_SUCCESS";
export const FEED_FAILURE = "FEED_FAILURE";

export const REFACTOR_FEED_LIKED_POST = "REFACTOR_FEED_LIKED_POST";
export const DECREMENT_COMMENT_COUNT_FEED = "DECREMENT_COMMENT_COUNT_FEED";
export const INCREMENT_COMMENT_COUNT_FEED = "INCREMENT_COMMENT_COUNT_FEED";
export const REFACTOR_FEED = "REFACTOR_FEED";

// Enrich Feed
export const FEED_ENRICH_REQUEST = "FEED_ENRICH_REQUEST";
export const FEED_ENRICH_SUCCESS = "FEED_ENRICH_SUCCESS";
export const FEED_ENRICH_FAILURE = "FEED_ENRICH_FAILURE";
export const ADD_TO_FEED_ON_ENRICH = "ADD_TO_FEED_ON_ENRICH";

export const RESET_UNREAD_COUNT = "RESET_UNREAD_COUNT";
export const INCREMENT_UNREAD_COUNT = "INCREMENT_UNREAD_COUNT";

// Repost
export const REPOST_REQUEST = "REPOST_REQUEST";
export const REPOST_SUCCESS = "REPOST_SUCCESS";
export const REPOST_FAILURE = "REPOST_FAILURE";

export const DEDICATED_POST_REQUEST = "DEDICATED_POST_REQUEST";
export const DEDICATED_POST_SUCCESS = "DEDICATED_POST_SUCCESS";
export const DEDICATED_POST_FAILURE = "DEDICATED_POST_FAILURE";

export const INCREMENT_COMMENT_COUNT_POST = "INCREMENT_COMMENT_COUNT_POST";
export const DECREMENT_COMMENT_COUNT_POST = "DECREMENT_COMMENT_COUNT_POST";
export const LIKE_POST = "LIKE_POST";

export const SET_TOKEN = "SET_TOKEN";

// User Profile

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";
export const USER_PROFILE_FEED_REQUEST = "USER_PROFILE_FEED_REQUEST";
export const USER_PROFILE_FEED_SUCCESS = "USER_PROFILE_FEED_SUCCESS";
export const USER_PROFILE_FEED_FAILURE = "USER_PROFILE_FEED_FAILURE";
export const FETCH_USER_MUSIC_SUCCESS = "FETCH_USER_MUSIC_SUCCESS";
export const FETCH_USER_MUSIC_FAILURE = "FETCH_USER_MUSIC_FAILURE";
export const FETCH_USER_MUSIC_REQUEST = "FETCH_USER_MUSIC_REQUEST";
export const FETCH_USER_IMAGES_SUCCESS = "FETCH_USER_IMAGES_SUCCESS";
export const FETCH_USER_IMAGES_FAILURE = "FETCH_USER_IMAGES_FAILURE";
export const FETCH_USER_IMAGES_REQUEST = "FETCH_USER_IMAGES_REQUEST";
export const REFACTOR_LIKED_PROFILE_POST = "REFACTOR_LIKED_PROFILE_POST";
export const INCREMENT_COMMENT_COUNT_USER_PROFILE_POST =
  "INCREMENT_COMMENT_COUNT_USER_PROFILE_POST";
export const DECREMENT_COMMENT_COUNT_USER_PROFILE_POST =
  "DECREMENT_COMMENT_COUNT_USER_PROFILE_POST";

export const SET_USER_SOCIAL = "SET_USER_SOCIAL";

/* MarketPlace */
/* Fetch Categories */
export const CATEGORIES_REQUEST = "CATEGORIES_REQUEST";
export const CATEGORIES_SUCCESS = "CATEGORIES_SUCCESS";
export const CATEGORIES_FAILURE = "CATEGORIES_FAILURE";

/* Publish Service */
export const PUBLISH_SERVICE_REQUEST = "PUBLISH_SERVICE_REQUEST";
export const PUBLISH_SERVICE_SUCCESS = "PUBLISH_SERVICE_SUCCESS";
export const PUBLISH_SERVICE_FAILURE = "PUBLISH_SERVICE_FAILURE";

/* Offered Services */
export const OFFERED_SERVICE_REQUEST = "OFFERED_SERVICE_REQUEST";
export const OFFERED_SERVICE_SUCCESS = "OFFERED_SERVICE_SUCCESS";
export const OFFERED_SERVICE_FAILURE = "OFFERED_SERVICE_FAILURE";

/* Header categories */
export const HEADER_CATEGORIES_REQUEST = "HEADER_CATEGORIES_REQUEST";
export const HEADER_CATEGORIES_SUCCESS = "HEADER_CATEGORIES_SUCCESS";
export const HEADER_CATEGORIES_FAILURE = "HEADER_CATEGORIES_FAILURE";

/* Fetch Services */
export const SERVICES_REQUEST = "SERVICES_REQUEST";
export const SERVICES_SUCCESS = "SERVICES_SUCCESS";
export const SERVICES_FAILURE = "SERVICES_FAILURE";

export const SERVICE_REQUEST = "SERVICE_REQUEST";
export const SERVICE_SUCCESS = "SERVICE_SUCCESS";
export const SERVICE_FAILURE = "SERVICE_FAILURE";

export const REVIEW_REQUEST = "REVIEW_REQUEST";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_FAILURE = "REVIEW_FAILURE";

/* Cart */
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";

export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE";

export const CHANGE_USER_CART_COUNT = "CHANGE_USER_CART_COUNT";
export const RESET_CART = "RESET_CART";

export const CART_REQUEST = "CART_REQUEST";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAILURE = "CART_FAILURE";

export const FETCH_CART_COUNT_REQUEST = "FETCH_CART_COUNT_REQUEST";
export const FETCH_CART_COUNT_SUCCESS = "FETCH_CART_COUNT_SUCCESS";
export const FETCH_CART_COUNT_FAILURE = "FETCH_CART_COUNT_FAILURE";

// Save payment details
export const PAYMENT_DETAILS_REQUEST = "PAYMENT_DETAILS_REQUEST";
export const PAYMENT_DETAILS_SUCCESS = "PAYMENT_DETAILS_SUCCESS";
export const PAYMENT_DETAILS_FAILURE = "PAYMENT_DETAILS_FAILURE";

// Fetch Card details
export const CARD_REQUEST = "CARD_REQUEST";
export const CARD_SUCCESS = "CARD_SUCCESS";
export const CARD_FAILURE = "CARD_FAILURE";

// Place Order
export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";

// Purchased Services
export const PURCHASED_SERVICE_REQUEST = "PURCHASED_SERVICE_REQUEST";
export const PURCHASED_SERVICE_SUCCESS = "PURCHASED_SERVICE_SUCCESS";
export const PURCHASED_SERVICE_FAILURE = "PURCHASED_SERVICE_FAILURE";

// Featured Services
export const FEATURED_SERVICES_REQUEST = "FEATURED_SERVICES_REQUEST";
export const FEATURED_SERVICES_SUCCESS = "FEATURED_SERVICES_SUCCESS";
export const FEATURED_SERVICES_FAILURE = "FEATURED_SERVICES_FAILURE";

// Search
export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
export const RESET_SEARCH_STATE = "RESET_SEARCH_STATE";

// Notification
export const NOTIFICATION_REQUEST = "NOTIFICATION_REQUEST";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";

export const NOTIFICATION_COUNT_REQUEST = "NOTIFICATION_COUNT_REQUEST";
export const NOTIFICATION_COUNT_SUCCESS = "NOTIFICATION_COUNT_SUCCESS";
export const NOTIFICATION_COUNT_FAILURE = "NOTIFICATION_COUNT_FAILURE";

// Reset Notification status
export const NOTIFICATION_RESET_REQUEST = "NOTIFICATION_RESET_REQUEST";
export const NOTIFICATION_RESET_SUCCESS = "NOTIFICATION_RESET_SUCCESS";
export const NOTIFICATION_RESET_FAILURE = "NOTIFICATION_RESET_FAILURE";
export const SET_NOTIFICATION_COUNT = "SET_NOTIFICATION_COUNT";

// Admin constants

// Fetch Users
export const ADMIN_USERS_REQUEST = "ADMIN_USERS_REQUEST";
export const ADMIN_USERS_SUCCESS = "ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_FAILURE = "ADMIN_USERS_FAILURE";

// Toggle Admin Access
export const TOGGLE_ACCESS_REQUEST = "TOGGLE_ACCESS_REQUEST";
export const TOGGLE_ACCESS_SUCCESS = "TOGGLE_ACCESS_SUCCESS";
export const TOGGLE_ACCESS_FAILURE = "TOGGLE_ACCESS_FAILURE";
export const REFACTOR_ADMIN_USER = "REFACTOR_ADMIN_USER";

// Marketplace Management
export const TOGGLE_ACTIVE_TAB = "TOGGLE_ACTIVE_TAB";
// Active Services
export const ACTIVE_SERVICES_REQUEST = "ACTIVE_SERVICES_REQUEST";
export const ACTIVE_SERVICES_SUCCESS = "ACTIVE_SERVICES_SUCCESS";
export const ACTIVE_SERVICES_FAILURE = "ACTIVE_SERVICES_FAILURE";
// Pending Services
export const PENDING_SERVICES_REQUEST = "PENDING_SERVICES_REQUEST";
export const PENDING_SERVICES_SUCCESS = "PENDING_SERVICES_SUCCESS";
export const PENDING_SERVICES_FAILURE = "PENDING_SERVICES_FAILURE";
// Service Detail
export const SERVICE_DETAIL_REQUEST = "SERVICE_DETAIL_REQUEST";
export const SERVICE_DETAIL_SUCCESS = "SERVICE_DETAIL_SUCCESS";
export const SERVICE_DETAIL_FAILURE = "SERVICE_DETAIL_FAILURE";
// Service Delete
export const SERVICE_DELETE_REQUEST = "SERVICE_DELETE_REQUEST";
export const SERVICE_DELETE_SUCCESS = "SERVICE_DELETE_SUCCESS";
export const SERVICE_DELETE_FAILURE = "SERVICE_DELETE_FAILURE";
// Service Approve
export const SERVICE_APPROVE_REQUEST = "SERVICE_APPROVE_REQUEST";
export const SERVICE_APPROVE_SUCCESS = "SERVICE_APPROVE_SUCCESS";
export const SERVICE_APPROVE_FAILURE = "SERVICE_APPROVE_FAILURE";
