# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CosoundApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CosoundApp
  
pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
pod 'Firebase/Core'
pod 'GoogleSignIn', '~> 4.4.0'
pod 'Fabric', '~> 1.10.1'
pod 'Crashlytics', '~> 3.13.1'

#pod 'RNGoogleSignin', :path => "rnfolder/node_modules/react-native-google-signin"

  
  # pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  #pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'


  target 'CosoundAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

